spring:
  application:
    name: master_data_service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
    show-sql: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwks-uri: ${PORTAL_JWKS_URI}

server:
  port: ${MASTER_DATA_PORT}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
