spring:
  application:
    name: master_data_service
  datasource:
    url: jdbc:postgresql://localhost:5432/master_data?reWriteBatchedInserts=true
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update        # đổi thành validate khi production
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        format_sql: true      # bỏ ở production
    show-sql: false           # bật true khi cần debug query
  security:
    oauth2:
      resourceserver:
        jwt:
          jwks-uri: http://localhost:8080/.well-known/jwks.json # endpoint lấy public key từ Portal

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs